manage_post/urls.py
from django.urls import path
from manage_post import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<slug:slug>', views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', views.ListAllCategoriesView.as_view(), name='all_categories'),
    path('article/<slug:slug>', views.ShowPostDetailView.as_view(), name='post'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('manage_post.urls')),
    path('user/', include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from user import views
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('add/', views.SignUpView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit/', views.UserUpdateView.as_view(), name='edit_user'),
    path('delete', views.UserDeleteView.as_view(), name='delete_user'),
    path('password/', views.PasswordsChangeView.as_view(), name='change_password'),
    path('profile/<int:pk>', views.ViewProfile.as_view(), name='view_profile'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='password/password_reset.html'
    ), name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='password/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='password/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='password/password_reset_complete.html'
    ), name='password_reset_complete'),
]

manage_post/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

#categorias
class Category(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(upload_to='Categories', blank=False, null=False)
    slug = models.SlugField(unique=True, max_length=40)
    featured = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

#articulos
class Article(models.Model):
    title = models.CharField(max_length=255)
    introduction = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField(upload_to='Articles', blank=False, null=False)
    body = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

#calificaciones
class Rating(models.Model):
    value = models.FloatField()
    description = models.CharField(max_length=255)
    article_id = models.ForeignKey(Article,on_delete=models.CASCADE)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.user_id.username

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'

manage_post/forms.py
from django import forms
from manage_post.models import Rating

class CommentForm(forms.ModelForm):

    CHOICES = [
        (5, str("5 " + chr(11088))),
        (4, str("4 " + chr(11088))),
        (3, str("3 " + chr(11088))),
        (2, str("2 " + chr(11088))),
        (1, str("1 " + chr(11088))),
    ]

    value = forms.ChoiceField(label='calificacion',
                              choices=CHOICES,
                              widget=forms.Select())

    description = forms.CharField(required=True,
                                  label=False,
                                  widget=forms.Textarea(attrs={'rows': 5, 'cols': 70, 'placeholder': 'Ingresa tu comentario aqui'}))

    class Meta:
        model = Rating
        fields = [
            'value',
            'description',
        ]

manage_post/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from manage_post.models import Article, Category
from manage_post.forms import CommentForm
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here
class IndexView(ListView):
    model = Article
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #Enviar un artículo: estado=True
        context['articles'] = Article.objects.filter(status=True)

        #Obtener la información de las categorías destacadas
        context['navbar_category'] = Category.objects.filter(featured=True)
        return context

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category_detail.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #Enviar artículos activos de acuerdo a su categoría
        context['articles'] = Article.objects.filter(status=True).filter(
            categories=Category.objects.get(slug=self.kwargs['slug'])
        )

        # Obtener la información de las categorías destacadas
        context['navbar_category'] = Category.objects.filter(featured=True)
        return context

class ListAllCategoriesView(ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'

class ShowPostDetailView(FormMixin, DetailView):
    model = Article
    template_name = 'article_detail.html'
    form_class = CommentForm
    context_object_name = 'article'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.article_id = Article.objects.get(slug=self.kwargs['slug'])
        form.instance.user_id = User.objects.get(id=self.request.user.id)

        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('post', kwargs={'slug': self.kwargs['slug']})

manage_post/templates/add_comment.html
<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/comments.css' %}">
{% endblock css%}

<div class="form-content">
    <form method="POST" class="form-general comments">
        <!-- Agregar token -->
        {% csrf_token %}
        <ul>
            <!-- Obtener formulario  -->
            {{ form.as_ul }}
        </ul>

        <!-- Asignar valor al input -->
        <input type="submit" value="Comentar" class="btn-submit btn-comment">
    </form>
</div>

manage_post/templates/article_detail.html
<!-- Heredar de base -->
{% extends 'base.html' %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/article_detail.css' %}">
{% endblock css %}

<!-- Bloque título -->
{% block title %} Post {% endblock title %}

<!-- Bloque contenido -->
{% block content %}

<div class="content-post">
    <div class="post-title line">
        <h2>{{ article.title }}</h2>
    </div>
    <div class="post-introduction line">
        <p{{ article.introduction }}</p>
    </div>
    <div class="post-author line">
        <!-- Imagen del autor del artículo -->
        {% if article.user_id.profile %}
        <img src="{{ article.user_id.profile_photo.url }}" class="img-author" alt="Autor Post">
        {% else %}
        <img src="{% static 'image/Default/default-user.png' %}" class="img-author" alt="Autor Post">
        {% endif %}
        <!-- Redirigir al perfil del autor -->
        <span>Autor: <a href="#">{{ article.user_id.full_name }}</a></span>
    </div>
    <hr>
    <div class="post-image">
        <!-- Imagen del artículo -->
        <img src="{{ article.image.url }}" alt="imagen" class="post-image-img">
    </div>
    <div class="post-body line">
        <p>{{ article.body|safe }}</p>
    </div>
    <hr>
</div>

<!-- Comentarios -->
<h2 class="text-primary">Comentarios:</h2>

<!-- Incluir agregar comentarios -->
{% if request.user.is_authenticated %}
{% include 'add_comment.html' %}
{% else %}
<p class="alert-post">Para comentar debe iniciar sesión</p>
{% endif %}

<!-- Incluir visualizar comentarios -->
{% include 'comments.html' %}
{% endblock content %}

manage_post/templates/base.html
<html>

<head>
    <!--  Cargar archivos estáticos  -->
    {% load static %}

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">

    <link href="{% static 'css/general.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/menu.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/footer.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Bloque css cambiante -->
    {% block css %} {% endblock css %}

    <title>{% block title %} {% endblock title %}</title>
</head>

<body>
<div class="content">
    <!-- Incluir menú -->
    {% include 'menu.html' %}

    <section class="section">
        <!-- Contenido cambiante -->
        {% block content %} {% endblock content %}
    </section>

    <!-- Incluir footer -->
    {% include 'footer.html' %}
</div>
</body>
</html>

manage_post/templates/category_detail.html
<!-- Heredar de base -->
{% extends 'base.html' %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/article_category.css' %}">
{% endblock css %}

<!-- Bloque título -->
{% block title %} {{ category.name }} {% endblock title %}

<!-- Bloque contenido -->
{% block content %}

<!-- Navbar category -->
{% include 'navbar_category.html' %}

<div class="text-primary">
    <h2>{{ category.name|upper }}</h2>
</div>

<div class="article-container">
    <!-- Listar artículos -->
    {% for article in articles %}
    <article class="article">
        <!-- Imagen del artículo -->
        <img src="{{ article.image.url }}" alt="" class="img">
        <div class="card-body">
            <!-- Identificador del artículo -->
            <a href="{% url 'post' article.slug %}">
                <h2 class="title">{{ article.title|truncatewords:13 }}</h2>
            </a>
            <p class="introduction">{{ article.introduction|truncatewords:25 }}</p>
        </div>
    </article>
    {% endfor %}
</div>
{% endblock content %}

manage_post/templates/category_list.html
<!-- Heredar de base -->
{% extends 'base.html' %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/article_category.css' %}">
{% endblock css %}

<!-- Bloque título -->
{% block title %} Categorías {% endblock title %}

<!-- Bloque contenido -->
{% block content %}

<!-- Navbar category -->
{% include 'navbar_category.html' %}


<div class="text-primary">
    <h2>TODAS LAS CATEGORIAS</h2>
</div>

<div class="article-container">
    <!-- Listar categorías -->
    {% for category in categories %}
    <article class="article category">
        <img src="{{ category.image.url }}" class="img">
        <div class="card-body">
            <!-- Slug de la categoría -->
            <a href="{% url 'category_detail' category.slug %}">
                <h2 class="title category">{{ category.name }}</h2>
            </a>
        </div>
    </article>
    {% endfor %}
</div>
{% endblock content %}

manage_post/templates/comments.html
<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/comments.css' %}">
{% endblock css%}

<div class="comments-content">
    <!-- Listar los comentarios -->
    {% for comment in article.rating_set.all %}
    <div class="comments-body">
        <span class="comment-head">{{ comment.user_id.full_name }} &nbsp; &nbsp; {{ comment.value }} </span>
        <p class="comment-description line">{{ comment.description }}</p>
        <span class="comment-date"><b>Realizado: </b>{{ comment.created }}</span>
    </div>
    <hr>
    {% endfor %}
</div>

manage_post/templates/footer.html
<footer class="footer margen-interno">
    <nav class="pie">
        <a href="https://edutin.com" target="_blank">Desarrollado por &copy; Edutin Academy</a>
    </nav>
</footer>

manage_post/templates/index.html
<!-- Heredar de base -->
{% extends 'base.html' %}

<!-- Cargar archivos estáticos -->
{% load static %}

<!-- Bloque css -->
{% block css %}
<link rel="stylesheet" href="{% static 'css/article_category.css' %}">
{% endblock css %}

<!-- Bloque título -->
{% block title %} ABC BLOG {% endblock title %}

<!-- Bloque contenido -->
{% block content %}

<!-- Navbar category -->
{% include 'navbar_category.html' %}

<div class="slogan">
    <div class="column1">
        <h2>ABCBlog</h2>
    </div>
    <div class="column2">
        <p>Hemos ayudado a más de 1 millon de personas a crecer profesionalmente. Estos artículos comparten concejos
            para
            la búsqueda de empleo, la productividad y el éxito laboral en diferentes áreas del conocimiento.</p>
    </div>
</div>

<div class="article-container">
    <!-- Listar artículos -->
    {% for article in articles %}
    <article class="article">
        <!-- Imagen del artículo -->
        <img src="{{ article.image.url }}" alt="" class="img">
        <div class="card-body">
            <!-- Identificador del artículo -->
            <a href="{% url 'post' article.slug %}">
                <h2 class="title">{{ article.title|truncatewords:13 }}</h2>
            </a>
            <p class="introduction">{{ article.introduction|truncatewords:25 }}</p>
        </div>
    </article>
    {% endfor %}
</div>
{% endblock content %}

manage_post/templates/menu.html
<!-- Cargar archivos estáticos -->
{% load static %}

<header class="header">
    <div class="menu">
        <div class="logo">
            <!--Logo-->
            <a href="{% url 'index' %}"><img src="{% static 'image/Logo/abc_company.png' %}" alt="Logo"></a>
        </div>
        <nav class="nav">
            {% if request.user.is_authenticated %}
            <ul class="profile">

                <li>
                    <!-- Imagen del usuario -->
                    {% if request.user.profile %}
                    <img src="{{ request.user_profile.photo.url }}" alt="Profile"
                         class="img-profile">
                    {% else %}
                    <img src="{% static 'image/Default/default-user.png' %}" alt="Profile"
                         class="img-profile">
                    {% endif %}
                    <!-- Nombre completo del usuario -->
                        <span class="name-user">{{ request.user.full_name }}</span>
                </li>

                <!-- Botón de editar perfil -->
                <li>
                    <a href="{% url 'edit_user' %}" class="btn-edit-profile">Editar perfil</a>
                </li>
                <!-- Verificar si el usuario es staff -->
                {% if request.user.is_staff == True %}
                <li>
                    <a href="{% url 'admin:index' %}" class="btn-admin">Ir al admin</a>
                </li>
                {% endif %}
                <!-- Botón de salir -->
                <li>
                    <a href="{% url 'logout' %}" class="loguot">Salir</a>
                </li>
            </ul>
            {% else %}
            <ul>
                <li>
                    {% url 'login' as url_login %}
                    {% url 'register' as url_register %}

                    {% if request.path == url_register %}
                    <a href="{% url 'login' %}" class="login">Iniciar sesión</a>
                    {% elif request.path == url_login %}
                    <a href="{% url 'register' %}" class="create">Crear cuenta</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="login">Iniciar sesión</a>
                    <a href="{% url 'register' %}" class="create">Crear cuenta</a>
                    {% endif %}
                </li>
            </ul>
            {% endif %}
        </nav>
    </div>
</header>

manage_post/templates/my_categories.html
<!-- Heredar de la plantilla base -->

<!-- Cargar archivos estáticos -->

<!-- Bloque css -->
<!-- Estilo 1 -->
<!-- Cerrar bloque css -->

<!-- Bloque título --><!-- Cerrar bloque de título -->

<!-- Bloque de contenido -->

<!-- Incluir navbar category -->

<div class="text-primary">
    <h2>MIS CATEGORIAS</h2>
</div>

<div class="article-container">
    <!--- Inicio del ciclo For -->
    <article class="article category">
        <!-- Imagen de la categoría -->
        <img src="#" alt="" class="img">
        <div class="card-body">
            <!-- Redirigir a la categoría -->
            <a href="#">
                <h2 class="title category">Nombre categoría</h2>
            </a>
        </div>
    </article>
    <!--- Fin del ciclo For -->
</div>
<!-- Cerrar bloque de contenido -->

manage_post/templates/navbar_category.html
<div class="category-container">
    <ul>

        <!-- Redirigir al index -->
        <li class="nav-item {% if request.path == '/' %} active {% endif %}"><a href="{% url 'index' %}">Todo</a></li>

        <!-- Listar categorías destacadas -->
        {% for category in navbar_category %}
        {% url 'category_detail' category.slug as the_url %}
        <li class="nav-item {% if request.path == the_url %} active {% endif %}">
            <a href="{% url 'category_detail' category.slug %}">{{ category.name }}</a>
        </li>
        {% endfor %}

        <!-- Listar todas las categorías -->
        <li class="nav-item ">
            <a href="{% url 'all_categories' %}">Todas las categorias</a>
        </li>

    </ul>
</div>